version: '3'
services:
  db:
    image: postgres
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -p 3000 -e production
    volumes:
      - .:/var/www
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db