default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
development:
  <<: *default
  database: parking_development
test:
  <<: *default
  database: parking_test
#
production:
  <<: *default
  database: parking_production